services:
  await-glibc-builder:
    build:
      context: .
      dockerfile: ./glibc-builder/Dockerfile
    image: await-glibc-builder
    depends_on:
      await-rootfs-builder:
        condition: service_completed_successfully
    volumes:
      - ./output/await-rootfs:/output/await-rootfs
      - ./glibc-2.35:/build/glibc-2.35  # ソースコードのマウント
    entrypoint: /bin/bash /app/scripts/exec_all.sh
  
  await-rootfs-builder:
    build:
      context: .
      dockerfile: ./rootfs-builder/Dockerfile
    privileged: true
    image: await-rootfs-builder
    volumes:
      - ./output:/output
    entrypoint: /app/scripts/download_base_rootfs.sh
  
  await-rootfs-server:
    build:
      context: .
      dockerfile: ./rootfs-server/Dockerfile
    image: await-rootfs-server
    volumes:
      - ./rootfs-server/data:/app/data
    ports:
      - 8101:80
