version: '3'
services:
  await-glibc-builder:
    build:
      context: .
      dockerfile: ./builder/Dockerfile
    image: await-glibc-builder
    volumes:
      - ./output:/output
      - ./glibc-2.35:/build/glibc-2.35  # ソースコードのマウント
